// Bundles the three command-line entry points into dist/, each one file with
// every dependency inlined.
//
// The Claude Code plugin runs these files straight from the cloned repository,
// and Claude Code does not run `npm install` for plugins, so nothing may be
// left to resolve from node_modules. dist/ is committed for the same reason;
// CI rebuilds it and fails when the committed copy is stale.
//
//   node scripts/build.mjs

import { build } from "esbuild";

const entries = {
	"brain-traverse": "pi-traverser/bin/brain-traverse.ts",
	"brain-keeper": "brain-keeper/bin/brain-keeper.ts",
	"brain-hook": "pi-traverser/bin/brain-hook.ts",
};

await build({
	entryPoints: entries,
	outdir: "dist",
	outExtension: { ".js": ".mjs" },
	bundle: true,
	platform: "node",
	target: "node22",
	format: "esm",
	// Bundled CommonJS dependencies may still call require() for Node builtins,
	// which an ES module does not have.
	banner: {
		js: [
			"#!/usr/bin/env node",
			"// Generated by scripts/build.mjs - do not edit.",
			'import { createRequire as __brainCreateRequire } from "node:module";',
			"const require = __brainCreateRequire(import.meta.url);",
		].join("\n"),
	},
	legalComments: "none",
	logLevel: "info",
});
